function displ = PazyWingLoad(fload,display)

% Load data
load('PazywWingData.mat','beam','shell','contour','nodes','sys');

% Assemble force vector
f = zeros(sys.ndof,1);
f(6*(nodes.force-1)+3,1) = -fload*9.81+fload*9.81*0.00025.*(1-randn(size(fload)));

% Compute displacements
u = zeros(sys.ndof,1);
u(sys.fdof,1) = sys.stiff(sys.fdof,sys.fdof)\f(sys.fdof);
U = reshape(u,6,[])';

% Get measurements
displ(:,1) = U(nodes.displ,3)+max(abs(U(nodes.displ,3)))*0.00025*(1-randn(length(nodes.displ),1));
displ(:,2) = nodes.coord(nodes.displ,1);
displ(:,3) = nodes.coord(nodes.displ,2);

% Plot
if exist('display','var') && display
    
    % Initialize figure
    figure
    hold on
    axis equal
    axis tight
    set(gca,'color','none','xcolor','none','ycolor','none','zcolor','none');
    view(140,15)

    % Separate coordinates and displacements
    X = nodes.coord(:,1);
    Y = nodes.coord(:,2);
    Z = nodes.coord(:,3);
    Ux = U(:,1);
    Uy = U(:,2);
    Uz = U(:,3);
    
    
    % Plot spar
    patch(...
        X(shell.spar)+Ux(shell.spar),...
        Y(shell.spar)+Uy(shell.spar),...
        Z(shell.spar)+Uz(shell.spar),...
        ones(size(shell.spar)),...
        'FaceColor',0.50*[1,1,1],...
        'EdgeColor','none'...
    );
    patch(...
        X(contour.spar)+Ux(contour.spar),...
        Y(contour.spar)+Uy(contour.spar),...
        Z(contour.spar)+Uz(contour.spar),...
        ones(size(contour.spar)),...
        'FaceColor','none',...
        'EdgeColor','k'...
    );

    % Plot ribs
    patch(...
        X(shell.ribs)+Ux(shell.ribs),...
        Y(shell.ribs)+Uy(shell.ribs),...
        Z(shell.ribs)+Uz(shell.ribs),...
        ones(size(shell.ribs)),...
        'FaceColor',0.95*[1,1,1],...
        'EdgeColor','none'...
    );
        patch(...
        X(contour.ribs)+Ux(contour.ribs),...
        Y(contour.ribs)+Uy(contour.ribs),...
        Z(contour.ribs)+Uz(contour.ribs),...
        ones(size(contour.ribs)),...
        'FaceColor','none',...
        'EdgeColor','k'...
    );

    % Plot leading edge beam axis
    patch(...
        X(beam.LE)+Ux(beam.LE),...
        Y(beam.LE)+Uy(beam.LE),...
        Z(beam.LE)+Uz(beam.LE),...
        ones(size(beam.LE)),...
        'FaceColor','none',...
        'EdgeColor','k'...
    );

    % Plot trailing edge beam axis
    patch(...
        X(beam.TE)+Ux(beam.TE),...
        Y(beam.TE)+Uy(beam.TE),...
        Z(beam.TE)+Uz(beam.TE),...
        ones(size(beam.TE)),...
        'FaceColor','none',...
        'EdgeColor','k'...
    );

    % Plot wing tip rod
    patch(...
        X(beam.tip)+Ux(beam.tip),...
        Y(beam.tip)+Uy(beam.tip),...
        Z(beam.tip)+Uz(beam.tip),...
        ones(size(beam.tip)),...
        'FaceColor','none',...
        'EdgeColor',0.5*[1,1,1],...
        'Linewidth',2 ...
    );

    % Plot origin axes
    mArrow3([0,0,0],[0.1,0,0],'color','r','stemWidth',0.002,'tipWidth',0.004); 
    text(0.1+0.01,0,0,'X','color','r','horizontalalignment','center');
    mArrow3([0,0,0],[0,0.1,0],'color','g','stemWidth',0.002,'tipWidth',0.004);
    text(0,0.1+0.01,0,'Y','color','g','horizontalalignment','center');
    mArrow3([0,0,0],[0,0,0.1],'color','b','stemWidth',0.002,'tipWidth',0.004);
    text(0,0,0.1+0.01,'Z','color','b','horizontalalignment','center');
    
    % Plot forces
    a  = nodes.force(fload~=0);
    fz = 0.1*fload(fload~=0)/max(abs(fload));
    for i = 1:length(a)
        xf = [X(a(i))+Ux(a(i)),Y(a(i))+Uy(a(i)),Z(a(i))+Uz(a(i))];
        mArrow3(xf,xf+[0,0,-fz(i)],'color','k','stemWidth',0.002,'tipWidth',0.004); 
    end
    
    % Plot sensors
    plot3(X(nodes.displ)+Ux(nodes.displ),Y(nodes.displ)+Uy(nodes.displ),Z(nodes.displ)+Uz(nodes.displ),'.r','markersize',10);
    
%     % Plot force slots
%     plot3(X(nodes.force)+Ux(nodes.force),Y(nodes.force)+Uy(nodes.force),Z(nodes.force)+Uz(nodes.force),'.w','markersize',7);
    
end

end